# Generated by Django 6.0.1 on 2026-01-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorymodel_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
